<!-- GitHub star -->
<a class="github-button" href="https://github.com/qiuchengw/siachart" data-icon="octicon-star" data-show-count="true" aria-label="Star qiuchengw/siachart on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/qiuchengw/siachart/fork" data-icon="octicon-repo-forked" data-show-count="true" aria-label="Fork qiuchengw/siachart on GitHub">Fork</a><!-- Tweet button -->
<!-- Twitter follow button 
<a href="https://twitter.com/qiuchengw" class="twitter-follow-button" data-show-count="true">Follow @hexojs</a>
-->
<!-- Github Button -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Twitter share button -->
<!-- <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script> -->
